Repository NordicSemiconductor/bluetooth-numbers-database, pull requests merged in 2024-01, with the labels that each got.

#107 Added JSON file with GAP appearance values from BT SiG
  v1/gap_appearance.json
Labels: enhancement

#109 Small README Fix
  README.md
Labels: documentation

#110 Appearances are now exported, and we also added missing scripts
  index.js
  v1/appearance_schema.json
  verify.js
Labels: documentation, enhancement
